// Products used by scheduled posts (writer b). Export `extra` as an array of P({...}) entries,
// same shape as src/products.mjs. Facts checked on maker pages and reviews, October 5, 2026.
const TAG = "bestgolfsenior-20";
const search = (q) => `https://www.amazon.com/s?k=${encodeURIComponent(q.replace(/[()']/g, "").replace(/\s+/g, " ").trim()).replace(/%20/g, "+")}&tag=${TAG}`;
const P = (o) => ({ merchant: "Amazon", amazon: true, url: search(o.q || o.name), go: o.id, ...o });

export const extra = [
  // ---------- Drivers (most-forgiving-driver) ----------
  P({ id: "b-g440-k", cat: "driver", short: "PING G440 K", name: "PING G440 K Driver", year: 2026, list: "$650 at launch (not part of PING's Aug 2026 price cut)",
    best: "Highest MOI we found",
    specs: ["9°, 10.5° or 12° (±1.5°)", "Combined MOI over 10,000 g-cm²", "32 g rear weight: draw, neutral or fade"],
    how: "Golf Digest's 2026 Hot List measured it as the highest-MOI driver tested, and Today's Golfer's 2026 data named it the best blend of forgiveness and distance.",
    drawback: "The priciest PING driver, and very slow swingers may launch a lighter club higher.",
    src: "https://www.golfdigest.com/story/ping-g440-k-driver--what-you-need-to-know" }),
  P({ id: "b-qi4d-max", cat: "driver", short: "TaylorMade Qi4D Max", name: "TaylorMade Qi4D Max Driver", year: 2026, list: "$649.99",
    best: "Most forgiving TaylorMade",
    specs: ["9°, 10.5° or 12°", "Combined MOI about 9,700 g-cm²", "Senior, Regular or Stiff flex"],
    how: "The highest-MOI head in TaylorMade's 2026 line, rated \"extreme\" for MOI on Golf Digest's 2026 Hot List, with a senior flex in stock options.",
    drawback: "Heavier than the Max Lite version, so slower swingers may lose a little speed.",
    src: "https://www.todays-golfer.com/news-and-events/equipment-news/everything-you-need-to-know-about-the-taylormade-qi4d-metalwoods" }),
  P({ id: "b-gt1-driver", cat: "driver", short: "Titleist GT1", name: "Titleist GT1 Driver", year: 2025, list: "$649.99",
    best: "Most forgiving under 90 mph (MyGolfSpy)",
    specs: ["9°, 10° or 12°", "Lightweight build: 9 g weight, 40 g shaft", "Standard build about 50 g heavier"],
    how: "Won MyGolfSpy's 2026 forgiveness category for swing speeds under 90 mph, with a 95.2% playable rate. Titleist built it for moderate speeds.",
    drawback: "No draw-biased head, so it won't fix a slice by itself.",
    src: "https://mygolfspy.com/news-opinion/6-things-you-should-know-before-you-buy-the-new-titleist-gt1-driver/" }),
  P({ id: "b-quantum-max-d", cat: "driver", short: "Callaway Quantum Max D", name: "Callaway Quantum Max D Driver", year: 2026, list: "$649.99",
    best: "Callaway's slice fighter",
    specs: ["9°, 10.5° or 12° (left-handed 9° or 10.5°)", "Internal heel weighting for draw", "Project X Denali 50 g, Regular"],
    how: "Fixed heel weight closes the face more easily. Plugged In Golf found the draw bias stronger than Callaway's \"slight\" label and called it excellent for slice correction.",
    drawback: "Stock shaft is Regular flex only; no adjustable weights.",
    src: "https://www.callawaygolf.com/product/drivers-2026-quantum-max-d" }),
  P({ id: "b-g440-max", cat: "driver", short: "PING G440 Max", name: "PING G440 Max Driver", year: 2025, list: "$619 at launch; $449 after PING's Aug 2026 price cut",
    best: "Best value high-MOI driver",
    specs: ["9°, 10.5° or 12°", "About 9,500 g-cm² combined MOI (9° head)", "Movable weight for draw or fade"],
    how: "Close to 10K forgiveness for $200 less than most 2026 drivers, after PING cut G440 prices in August 2026.",
    drawback: "Two seasons old, and a G440 successor is expected in early 2027.",
    src: "https://golf.com/gear/drivers/ping-g440-drivers-woods-hybrids/" }),

  // ---------- Single length irons ----------
  P({ id: "b-king-tec-x-ol", cat: "irons", short: "Cobra King Tec-X One Length", name: "Cobra King Tec-X One Length Irons", year: 2025, list: "$1,299 (7 clubs, 5-GW)",
    best: "Best current one-length iron",
    specs: ["Every iron at 7-iron length", "Hollow body, 70 g tungsten in the toe", "5-6 irons: wider soles, weaker lofts", "Steel stock; graphite custom order"],
    how: "Cobra has sold one-length irons since 2017 and is the only big brand we found still selling them. The Tec-X head is hollow and slightly larger than a players' iron, with extra help in the long irons.",
    drawback: "Aimed at 10-20 handicaps, the stock steel is heavy for many seniors, and graphite is custom-order only.",
    src: "https://golfwrx.com/?p=748640" }),
  P({ id: "b-darkspeed-ol", cat: "irons", short: "Cobra Darkspeed One Length", name: "Cobra Darkspeed One Length Irons", year: 2024, list: "$999 steel, $1,099 graphite (at launch)",
    best: "Game-improvement one-length (older model)",
    specs: ["All irons 37.25 inches", "7-iron 27°, PW 42°", "Graphite KBS PGI in 65 g Lite (custom)"],
    how: "Cobra's 2024 game-improvement one-length set (the Tec-X is a \"players game-improvement\" iron), with a Lite graphite shaft available to order.",
    drawback: "A 2024 model; stock is thinning, so check for a new set rather than old retailer stock.",
    src: "https://drivingrangeheroes.com/cobra-golf-introduces-all-new-darkspeed-variable-and-one-length-irons/" }),
  P({ id: "b-majek-sl-hybrids", cat: "hybrid-irons", short: "Majek Senior Single Length hybrid set", name: "Majek Senior Single Length All-Hybrid Set (#3-PW)", year: null, list: "$399.95–469.95",
    q: "Majek senior single length hybrid set",
    best: "Best budget one-length set for seniors",
    specs: ["8 hybrids, #3 (20°) to PW (45°)", "All 38 inches; -1 or +1 inch options", "Senior-flex graphite; right- or left-handed"],
    how: "A whole set of hybrid heads at one length with a true senior flex, for about a third of the price of the Cobra irons.",
    drawback: "A small brand with no independent launch-monitor testing we could find.",
    src: "https://majekgolf.com/products/senior-single-length-one-length-men-s-majek-golf-all-hybrid-complete-full-set-which-includes-3-4-5-6-7-8-9-pw-senior-flex-total-of-8-right-handed-new-utility-a-flex-clubs" }),
  P({ id: "b-king-tec-ol-hybrid", cat: "hybrid", short: "Cobra King Tec One Length hybrid", name: "Cobra King Tec One Length Hybrid", year: 2025, list: "$299 at launch; $319 on Cobra's site (Oct 2026)",
    best: "One-length hybrid to top off a set",
    specs: ["3H 19°, 4H 21°, 5H 24°", "All 37.25 inches (7-iron length)", "Graphite Lite or Regular; ±2° hosel"],
    how: "Replaces the long irons in a one-length set without giving up the single setup, and it comes in a Lite graphite flex.",
    drawback: "Right-handed only, and Cobra aims it at better players.",
    src: "https://golfwrx.com/753135/cobra-announces-king-tec-king-tec-one-length-hybrids/" }),
  P({ id: "b-avoda-origin-sl", cat: "irons", short: "Avoda Origin Same Length", name: "Avoda Origin Same Length Irons", year: null, list: "From $985 (Avoda's site, Oct 2026)",
    best: "Forged one-length for better players",
    specs: ["Forged carbon steel, muscle-cavity", "4-PW or 4-LW sets", "Chrome or black finish"],
    how: "Soft-feeling forged irons sold in same-length sets. Golf Monthly praised the feel and turf interaction.",
    drawback: "Small, forged heads; not built for forgiveness.",
    src: "https://golfmonthly.com/reviews/irons/avoda-origin-same-length-irons-review" }),

  // ---------- Fairway woods (best-7-wood) ----------
  P({ id: "b-quantum-max-fw", cat: "fairway", short: "Callaway Quantum Max fairway", name: "Callaway Quantum Max Fairway Wood", year: 2026, list: "$399.99",
    best: "Most high-loft options",
    specs: ["7W 21°, 9W 24°, 11W 27° (plus HVN 20°)", "Mitsubishi Vanquish 50 g, Senior or Regular", "Right- and left-handed (most lofts)"],
    how: "The only major-brand 2026 fairway sold as a 7-, 9- and 11-wood, with a light senior-flex shaft as a stock option.",
    drawback: "The 7-, 9- and 11-wood heads aren't adjustable.",
    src: "https://www.carlsgolfland.com/callaway-quantum-max-fairway-woods" }),
  P({ id: "b-gt1-fw", cat: "fairway", short: "Titleist GT1 fairway", name: "Titleist GT1 Fairway Wood", year: 2025, list: "$399",
    best: "Lightest Titleist fairway",
    specs: ["15°, 18°, 21° (7-wood) or 24° (9-wood)", "Fujikura Air Speeder 40 g, R2, R or S", "Deep, low center of gravity"],
    how: "Titleist built GT1 for moderate swing speeds: light shafts as standard and a shallow face that gets the ball up from the turf.",
    drawback: "Nothing above 24°, and pricier than PING's discounted G440.",
    src: "https://golfwrx.com/752680/gt1-driver-fairway-woods-hybrid-join-the-titleist-gt-family/" }),
  P({ id: "b-optm-max-fw", cat: "fairway", short: "Cobra OPTM Max fairway", name: "Cobra OPTM Max Fairway Wood", year: 2026, list: "$369",
    best: "Most adjustable 7-wood",
    specs: ["7W 21.5° (19.5°–23.5°), 9W 24.5° (22.5°–26.5°)", "Kai'li 50 g in Lite (A), Regular or Stiff", "Movable 14 g weight; heel setting for a slice"],
    how: "Every loft, including the 7- and 9-wood, has a ±2° hosel and a sliding weight you can move toward the heel to fight a slice.",
    drawback: "Lots of settings to sort through; 33 hosel positions can be more confusing than useful.",
    src: "https://www.golfbox.com.au/clubs/cobra-optm-max-fairway-wood/" }),

  // ---------- Travel bags (best-golf-travel-bag) ----------
  P({ id: "b-clubglider-meridian", cat: "bag", short: "Sun Mountain ClubGlider Meridian", name: "Sun Mountain ClubGlider Meridian Travel Bag", year: null, list: "$380",
    best: "Best overall; easiest to pull",
    specs: ["11.3 lb", "52 × 14 × 14 in inside", "Fold-out legs and pivoting wheels carry the weight"],
    how: "Its legs and front wheels take the load, so you push it like a cart instead of dragging it on two wheels. MyGolfSpy ranked it first of 25 travel bags in 2026.",
    drawback: "Heavier than most soft covers, and bulky to store.",
    src: "https://www.sunmountain.com/products/cg-meridian-19897" }),
  P({ id: "b-bagboy-t10", cat: "bag", short: "Bag Boy T-10", name: "Bag Boy T-10 Hard Top Travel Cover", year: null, list: "$229.95",
    best: "Best hard-top for the money",
    specs: ["9.6 lb", "Crush-resistant ABS hard top", "Inline-skate wheels; fabric body stores inside the top"],
    how: "A hard shell over the clubheads, where the damage happens, with a light fabric body below. It weighs about the same as soft covers.",
    drawback: "One-year warranty, shorter than most rivals.",
    src: "https://www.bagboy.com/products/t-10-travel-cover" }),
  P({ id: "b-caddydaddy-first-class", cat: "bag", short: "CaddyDaddy First Class", name: "CaddyDaddy First Class Golf Travel Bag", year: null, list: "$239.95",
    best: "Best value soft bag",
    specs: ["10 lb", "51 × 15 × 13 in", "Foam plus semi-rigid padded top; 2-year warranty"],
    how: "MyGolfSpy's best-value pick in 2026, with a warranty that CaddyDaddy says covers airline damage.",
    drawback: "Rolls on two wheels, so you tilt and pull it.",
    src: "https://caddydaddygolf.com/products/first-class-golf-travel-bag" }),
  P({ id: "b-clubglove-tour-traveler-sb", cat: "bag", short: "Club Glove Tour Traveler SB", name: "Club Glove Tour Traveler SB Travel Bag", year: null, list: "$550",
    best: "Best premium (stiff arm included)",
    specs: ["11.2 lb", "52 × 13 × 13 in, for stand bags", "Stiff arm, TSA lock, 5-year warranty"],
    how: "Heavy Cordura nylon, a padded clubhead area and a stiff arm in the box. MyGolfSpy's best premium pick for 2026.",
    drawback: "Expensive, and sized for stand bags, not big cart bags.",
    src: "https://www.clubglove.com/golf-travel-bags/tour/tour-traveler-sb/CG25TVTSB.html" }),
  P({ id: "b-ogio-renegade", cat: "bag", short: "OGIO Renegade", name: "OGIO Renegade Golf Travel Cover", year: null, list: "$385",
    best: "Toughest base and wheels",
    specs: ["12.7 lb", "54 × 13.4 × 13.4 in", "Impact-resistant base, oversized off-road wheels"],
    how: "Big wheels and a hard base handle curbs, gravel and rough sidewalks. MyGolfSpy scored it 9.6, just behind the Meridian.",
    drawback: "The heaviest soft bag here.",
    src: "https://www.ogio.com/golf/golf-bags/golf-travel-bags/ogio-accessories-2025-travel-cover-renegade.html" }),
  P({ id: "b-vault-hard-case", cat: "bag", short: "The Vault hard case", name: "Golf Travel Bags The Vault Hard Case", year: null, list: "$249.99",
    q: "Golf Travel Bags Vault hard case golf travel bag",
    best: "Full hard shell",
    specs: ["18 lb", "51 × 15 × 14.25 in", "Polyethylene shell, locking latches, made in USA"],
    how: "The most protection here: a full hard case with latches, which fits cart bags and oversized drivers.",
    drawback: "At 18 lb empty, it eats into a 50 lb airline limit and is hard to lift.",
    src: "https://www.golfdiscount.com/collections/golf-travel-bags/products/golf-travel-bags-the-vault-hard-case-travel-bag" }),
  P({ id: "b-clubglove-stiff-arm", cat: "bag-accessory", short: "Club Glove Stiff Arm", name: "Club Glove Stiff Arm", year: null, list: "$35",
    best: "Cheap insurance for your driver",
    specs: ["1.2 lb", "3-piece telescoping aluminum", "Rubber foot; comes apart for storage"],
    how: "Set it a little taller than your driver so a dropped or stacked-on bag hits the rod, not the clubhead. Club Glove says it absorbs the full force of impact.",
    drawback: "One more thing to pack, and it adds a little weight.",
    src: "https://www.clubglove.com/accessories/stiff-arm/stiff-arm/CG24STF.html" }),
];

// Art for the new "bag" category: an upright rolling travel cover (illustration, no logos).
export const art = {
  bag: `<svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 240 180" role="img" aria-label="Illustration of a padded golf travel bag on wheels"><rect width="240" height="180" rx="14" fill="#F4EFE3"/><ellipse cx="120" cy="164" rx="70" ry="6" fill="#17352A" opacity=".08"/>
<rect x="92" y="14" width="56" height="12" rx="6" fill="#2B2F34"/>
<path d="M84 34c0-10 8-16 18-16h36c10 0 18 6 18 16v116c0 6-4 10-10 10H94c-6 0-10-4-10-10z" fill="#1E2328" stroke="#17352A" stroke-width="2"/>
<path d="M84 34c0-10 8-16 18-16h36c10 0 18 6 18 16v26H84z" fill="#2F6B4F"/>
<path d="M120 22v136" stroke="#3A4048" stroke-width="2" stroke-dasharray="3 3"/>
<rect x="96" y="80" width="48" height="40" rx="6" fill="#2B2F34" stroke="#3A4048" stroke-width="2"/><path d="M104 92h32" stroke="#AEB6BD" stroke-width="2.5" stroke-linecap="round"/>
<rect x="110" y="62" width="20" height="8" rx="4" fill="#AEB6BD"/>
<circle cx="96" cy="160" r="9" fill="#2B2F34" stroke="#AEB6BD" stroke-width="3"/><circle cx="144" cy="160" r="9" fill="#2B2F34" stroke="#AEB6BD" stroke-width="3"/></svg>`,
};
