// Products used by scheduled posts (writer a). Export `extra` as an array of P({...}) entries,
// same shape as src/products.mjs.
// Checked October 5, 2026 on maker pages, Golf Digest Hot List 2026, MyGolfSpy and retailer spec pages.
const TAG = "bestgolfsenior-20";
const search = (q) => `https://www.amazon.com/s?k=${encodeURIComponent(q.replace(/[()']/g, "").replace(/\s+/g, " ").trim()).replace(/%20/g, "+")}&tag=${TAG}`;
const P = (o) => ({ merchant: "Amazon", amazon: true, url: search(o.q || o.name), go: o.id, ...o });
export const extra = [
  // ---------- Irons (most-forgiving-irons) ----------
  P({ id: "a-quantum-max-os-irons", cat: "irons", short: "Callaway Quantum Max OS irons", name: "Callaway Quantum Max OS Irons", year: 2026, list: "$164 per iron",
    q: "Callaway Quantum Max OS irons",
    best: "Best overall super game-improvement iron",
    specs: ["7-iron 29°; oversize head, extra offset, thick topline", "4-iron to SW sold; right- or left-handed", "Stock steel True Temper Elevate 85 (Regular); women's version in 40 g graphite"],
    how: "Scored a perfect 5.0 (Gold) in the super-game-improvement group of Golf Digest's 2026 Hot List. The oversize head looks reassuring at address, and Callaway offers a weaker-loft custom option for higher flight.",
    drawback: "The stock steel shaft is heavy for slower swings; order graphite if your driver speed is under about 85 mph.",
    src: "https://www.callawaygolf.com/golf-clubs/iron-sets/irons-2026-quantum-max-os.html" }),
  P({ id: "a-king-max-irons", cat: "irons", short: "Cobra King Max irons", name: "Cobra King Max Irons", year: 2026, list: "$999 steel / $1,099 graphite (set)",
    q: "Cobra King Max irons",
    best: "Most consistent on mis-hits",
    specs: ["7-iron 29.5°, about 2° weaker than Cobra's King", "Skid sole to reduce fat shots", "Steel or graphite; women's version sold"],
    how: "Won MyGolfSpy's 2026 forgiveness ranking for super-game-improvement irons: ball speed, carry, spin and dispersion changed the least when strikes moved off center.",
    drawback: "Lots of offset in the long irons, and a firmer feel than Cobra's forged models.",
    src: "https://mygolfspy.com/reviews/irons/cobra-king-max/" }),
  P({ id: "a-srixon-zxir-irons", cat: "irons", short: "Srixon ZXiR irons", name: "Srixon ZXiR Irons", year: 2026, list: "$1,099.99 steel / $1,199.99 graphite (7 irons)",
    q: "Srixon ZXiR irons",
    best: "Most forgiving game-improvement iron",
    specs: ["7-iron 28.5° (ZXiR HL: 32.5°)", "Softer i-Alloy steel head, wider sole", "HL and women's HL versions for slower swings"],
    how: "Ranked first for forgiveness in MyGolfSpy's 2026 game-improvement test and earned Gold in the Golf Digest Hot List. It looks more like a normal iron than the oversize picks, so it suits mid-to-high handicaps who want to keep it a few years.",
    drawback: "Less help with launch than the super-game-improvement picks unless you choose the HL version.",
    src: "https://golfwrx.com/769567/srixon-launches-new-zxir-and-zxir-hl-irons/" }),
  P({ id: "a-jpx925-hm-hl", cat: "irons", short: "Mizuno JPX925 Hot Metal HL irons", name: "Mizuno JPX925 Hot Metal HL Irons", year: 2024, list: "$165 per iron (launched at $149.99)",
    q: "Mizuno JPX925 Hot Metal HL irons",
    best: "Highest launch from a mid-price iron",
    specs: ["7-iron 31°, up to 3° weaker than the standard Hot Metal", "Chromoly steel face", "Steel or graphite shafts"],
    how: "Mizuno's most forgiving Hot Metal model, built for slow-to-moderate speeds. It scored 5.0 (Gold) in Golf Digest's 2026 super-game-improvement group.",
    drawback: "Launched in fall 2024, so it's the oldest design in this list; firm, 'hot' feel rather than soft.",
    src: "https://golf.com/clubpage/mizuno-jpx-925-forged-hot-metal-irons-reviews-player-testing-2025/" }),

  // ---------- Balls (best-golf-balls-for-high-handicappers) ----------
  P({ id: "a-warbird", cat: "ball", short: "Callaway Warbird", name: "Callaway Warbird Golf Balls (2025)", year: 2025, list: "$21.99 a dozen",
    q: "Callaway Warbird golf balls",
    best: "Cheapest major-brand dozen",
    specs: ["2-piece, large high-energy core", "Ionomer cover, distance design", "White or yellow"],
    how: "The lowest maker price per dozen of any major-brand ball here, built for distance off the tee. If you lose several balls a round, this is the one to stock up on.",
    drawback: "Firm feel and little greenside spin.",
    src: "https://www.globalgolf.com/golf-balls/1083468-callaway-warbird-2025-golf-ball/" }),
  P({ id: "a-duo-soft", cat: "ball", short: "Wilson Duo Soft", name: "Wilson Duo Soft Golf Balls (2025)", year: 2025, list: "$22.99 a dozen",
    q: "Wilson Duo Soft golf balls 2025",
    best: "Softest feel for the money",
    specs: ["Compression about 37 (maker)", "2-piece, low spin", "White, red, orange, green, yellow, pink"],
    how: "One of the lowest-compression balls sold, with high launch and low spin off the driver. Six colors make it easy to spot.",
    drawback: "Golf Monthly found it weak on approach and chip-shot control.",
    src: "https://mygolfspy.com/news-opinion/the-new-wilson-duo-soft-three-cool-things-and-one-uncool-thing/" }),
  P({ id: "a-velocity", cat: "ball", short: "Titleist Velocity", name: "Titleist Velocity Golf Balls (2026)", year: 2026, list: "$29.99 a dozen",
    q: "Titleist Velocity golf balls 2026",
    best: "Most distance-focused",
    specs: ["2-piece; softer core, fast cover for 2026", "Low long-game spin", "White, orange or green"],
    how: "In Today's Golfer's robot test it was the best two-piece ball for distance, with the lowest approach spin (that test may have used the previous version). Orange and green versions are easy to track.",
    drawback: "Firm, and the priciest ball here; low spin means approach shots release more.",
    src: "https://www.parwestgolf.com/products/titleist-2026-velocity-golf-balls" }),

  // ---------- Push carts (best-golf-push-cart) ----------
  P({ id: "a-nitron-swivel", cat: "cart", short: "Bag Boy Nitron Swivel", name: "Bag Boy Nitron Swivel Push Cart", year: null, list: "$359.95",
    q: "Bag Boy Nitron Swivel push cart",
    best: "Best overall push cart",
    specs: ["18.5 lb; folds to 18.7 × 13 × 22 in", "Auto-open (gas piston); 3 wheels, front swivels or locks", "Dual rear-wheel brake"],
    how: "Co-winner of MyGolfSpy's 2026 push cart test. A gas piston pops it open in one motion, and the swivel front wheel turns without lifting the front end.",
    drawback: "Costs $40 more and weighs almost 2 lb more than the plain Nitron.",
    src: "https://www.golfdiscount.com/products/bagboy-nitron-swivel-push-cart" }),
  P({ id: "a-bagboy-nitron", cat: "cart", short: "Bag Boy Nitron", name: "Bag Boy Nitron Push Cart", year: null, list: "$319.95",
    q: "Bag Boy Nitron push cart",
    best: "Lightest one-motion fold",
    specs: ["16.7 lb; folds to 19 × 13.5 × 22 in", "Auto-open (gas piston); 3 wheels", "Handle-mounted parking brake"],
    how: "The lightest cart in this guide, and it opens and folds in one motion with no latches. That matters when you lift it in and out of the trunk every time you play.",
    drawback: "Fixed front wheel, so tight turns take a little more effort than the Swivel.",
    src: "https://www.bagboy.com/products/nitron" }),
  P({ id: "a-clicgear-45", cat: "cart", short: "Clicgear Model 4.5", name: "Clicgear Model 4.5 Push Cart", year: null, list: "$339",
    q: "Clicgear Model 4.5 push cart",
    best: "Smallest folded footprint",
    specs: ["21 lb; folds to 13 × 15 × 23 in", "3 wheels; front-wheel hand brake", "Fits most stand bags"],
    how: "Runner-up in MyGolfSpy's 2026 test. It folds into the smallest box here, handy for a small trunk, and the console has a phone holder and drink holder built in.",
    drawback: "At 21 lb it's one of the heavier carts to lift.",
    src: "https://www.clicgearusa.com/products/clicgear-model-4-5-golf-push-cart" }),
  P({ id: "a-clicgear-8plus", cat: "cart", short: "Clicgear Model 8.0+", name: "Clicgear Model 8.0+ Push Cart", year: null, list: "$359",
    q: "Clicgear Model 8.0+ push cart",
    best: "Most stable on hills (4 wheels)",
    specs: ["22 lb; folds to 27 × 15 × 17 in", "4 wheels; dual front-wheel hand brake", "Slide-to-close fold"],
    how: "Four wheels and a wide stance make it hard to tip on side slopes, and you can lean on it without it rolling away.",
    drawback: "Heaviest pick here, and Clicgear says it's for cart bags, not stand bags.",
    src: "https://www.clicgearusa.com/products/clicgear-model-8plus-golf-push-cart" }),
  P({ id: "a-speed-cart-x", cat: "cart", short: "Sun Mountain Speed Cart X", name: "Sun Mountain Speed Cart X Push Cart", year: null, list: "$330",
    q: "Sun Mountain Speed Cart X push cart",
    best: "Easiest to push",
    specs: ["18.6 lb; 3 wheels", "Two-step fold", "Upgraded brake cable"],
    how: "MyGolfSpy's staff pick. Sun Mountain's three-wheel Speed Cart design dates to 1999, and the X is the latest version.",
    drawback: "Sun Mountain doesn't publish a folded size, so measure your trunk against a store model.",
    src: "https://www.tgw.com/p/sun-mountain-speed-cart-x-golf-push-cart/-/YT0zMDI2NTc1" }),
  P({ id: "a-sm-px4", cat: "cart", short: "Sun Mountain Pathfinder PX4", name: "Sun Mountain Pathfinder PX4 Push Cart", year: 2026, list: "$330",
    q: "Sun Mountain Pathfinder PX4 push cart",
    best: "Lightest 4-wheel cart",
    specs: ["17.2 lb; 4 wheels", "Two-step E-Z Latch fold", "Hand lever brake; one-piece handle"],
    how: "The lightest four-wheel cart we found, so you get the stability of four wheels without the weight of the Clicgear 8.0+.",
    drawback: "No published folded size, and not tested in MyGolfSpy's 2026 roundup.",
    src: "https://sunmountain.com/products/px4-push-cart" }),
  P({ id: "a-cybercart-push", cat: "cart", short: "Alphard Cybercart Push+", name: "Alphard Cybercart Push+ Push Cart", year: null, list: "$299 (often $199 on sale)",
    q: "Alphard Cybercart Push plus golf push cart",
    best: "Best value; can be motorized later",
    specs: ["23 lb; folds to 20 × 15.5 × 22 in", "3 wheels, swivel front; dual rear brakes", "Optional motor kit turns it into a remote electric caddy"],
    how: "Co-winner of MyGolfSpy's 2026 test at the lowest price of the top carts. If walking gets harder later, Alphard sells a motor kit instead of a whole new cart.",
    drawback: "Heaviest cart here to lift into a car.",
    src: "https://www.alphardgolf.com/products/cybercart-push" }),

  // ---------- Wedges (best-wedges-for-high-handicappers) ----------
  P({ id: "a-callaway-cb12", cat: "wedge", short: "Callaway CB12", name: "Callaway CB12 Wedge", year: 2025, list: "$179.99 steel / $189.99 graphite",
    q: "Callaway CB12 wedge",
    best: "Cavity back with high bounce",
    specs: ["50°–60° in 2° steps", "12° or 14° bounce, wide tri-sole", "KBS Hi-Rev steel or Project X Denali graphite"],
    how: "Every loft comes with 12° or more of bounce, which is what most high handicappers need: the wide sole skids through turf and sand instead of digging.",
    drawback: "No low-bounce option, so it's less suited to very firm, tight lies.",
    src: "https://www.golfdiscount.com/collections/golf-clubs-wedges-mens/products/callaway-cb12-wedge-2025" }),
  P({ id: "a-hl-max-d-wedge", cat: "wedge", short: "Tour Edge Hot Launch Max D wedge", name: "Tour Edge Hot Launch Max D Wedge", year: 2026, list: "$100",
    q: "Tour Edge Hot Launch Max D wedge",
    best: "Best budget wedge",
    specs: ["52°, 56° or 60°", "Extra-wide cambered sole, undercut cavity", "Full-face grooves"],
    how: "About half the price of the major brands, with the wide sole and full-face grooves of a specialty 'easy' wedge. The regular Hot Launch Max ($90, 50°–60°, 12° bounce) suits golfers who want a more normal look.",
    drawback: "Only three lofts, and fewer independent reviews than Cleveland or Callaway.",
    src: "https://www.australiangolfdigest.com.au/tour-edge-hot-launch-max-drivers-woods-hybrids-irons-wedges/" }),
  P({ id: "a-ping-chipr", cat: "wedge", short: "PING ChipR", name: "PING ChipR", year: 2022, list: "$195 steel / $210 graphite",
    q: "PING ChipR chipper",
    best: "Best chipper for chunks and skulls",
    specs: ["38.5° loft (about a 9-iron)", "35 in, putter-style 70° lie", "8° bounce; legal for play"],
    how: "You make a putting stroke and the loft does the rest, which removes the wrist action behind most chunked and bladed chips. PING recommends it for shots inside 40 yards.",
    drawback: "A specialty club: it doesn't replace a sand wedge from bunkers or for pitches.",
    src: "https://www.golfdigest.com/story/what-you-need-to-know--ping-chipr" }),
];

// Art for the new "cart" category (3-wheel push cart with a cart bag). Same palette as src/illus.mjs.
const BG = "#F4EFE3", INK = "#17352A", FRAME = "#AEB6BD", DARK = "#1E2328", BAG = "#2F6B4F", TIRE = "#2B2F34";
const wheel = (cx, cy, r) => `<circle cx="${cx}" cy="${cy}" r="${r}" fill="${TIRE}"/><circle cx="${cx}" cy="${cy}" r="${r * 0.45}" fill="${FRAME}"/>`;
export const art = {
  cart: `<svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 240 180" role="img" aria-label="Illustration of a three-wheel golf push cart carrying a golf bag"><rect width="240" height="180" rx="14" fill="${BG}"/><ellipse cx="120" cy="162" rx="92" ry="6" fill="${INK}" opacity=".08"/>
<path d="M58 146L112 60" stroke="${FRAME}" stroke-width="6" stroke-linecap="round"/><path d="M112 60L188 146" stroke="${FRAME}" stroke-width="6" stroke-linecap="round"/><path d="M112 60L150 22" stroke="${FRAME}" stroke-width="6" stroke-linecap="round"/>
<rect x="140" y="14" width="34" height="10" rx="5" fill="${DARK}" transform="rotate(-10 157 19)"/><path d="M144 34h26l-4 10h-22z" fill="${DARK}"/>
<g transform="rotate(-30 98 98)"><rect x="84" y="40" width="34" height="96" rx="12" fill="${BAG}" stroke="${INK}" stroke-width="2"/><rect x="80" y="38" width="42" height="14" rx="6" fill="${DARK}"/><rect x="92" y="78" width="20" height="26" rx="5" fill="#245640"/><path d="M90 38l-4-20M100 38l0-24M110 38l6-20" stroke="${FRAME}" stroke-width="3" stroke-linecap="round"/><path d="M82 18c-6-4-2-10 6-8l6 3-4 6z" fill="${DARK}"/><path d="M96 12l8-2 2 6-9 2z" fill="${FRAME}"/><path d="M114 16l9-1 1 6-9 2z" fill="${FRAME}"/></g>
${wheel(58, 146, 15)}${wheel(188, 146, 15)}${wheel(146, 152, 9)}<path d="M112 60L146 152" stroke="${FRAME}" stroke-width="4" stroke-linecap="round"/></svg>`,
};
