import { extra as extraA } from "./products-posts-a.mjs";
import { extra as extraB } from "./products-posts-b.mjs";
// Product facts verified on maker pages and independent reviews (Golf Digest, MyGolfSpy,
// GOLF.com, GolfWRX, Today's Golfer, golfalot), October 4, 2026. See research/products.md.
// `list` is the maker's list price (US$), shown as such. We never show Amazon prices
// (Associates policy). Links go to an Amazon search so shoppers see current sellers and prices.
export const CHECKED = "October 2026";
export const TAG = "bestgolfsenior-20";
const search = (q) => `https://www.amazon.com/s?k=${encodeURIComponent(q.replace(/[()']/g, "").replace(/\s+/g, " ").trim()).replace(/%20/g, "+")}&tag=${TAG}`;
const P = (o) => ({ merchant: "Amazon", amazon: true, url: search(o.q || o.name), go: o.id, ...o });

const list = [
  // ---------- Drivers ----------
  P({ id: "qi4d-max-lite", es: { best: "El mejor para velocidades moderadas", list: "US$649.99", specs: ["460cc; 10,5° o 12° (ajustable ±2°)", "Varilla Senior de 43 g o Regular de 44 g", "Cabeza, varilla y grip livianos"], how: "Todo el palo es liviano, así que el mismo esfuerzo se convierte en más velocidad. Quedó entre los más indulgentes en la prueba de drivers 2026 de MyGolfSpy.", drawback: "Es caro, y a los que pegan rápido no les aporta mucho." }, cat: "driver", short: "TaylorMade Qi4D Max Lite", name: "TaylorMade Qi4D Max Lite Driver", year: 2026, list: "$649.99",
    best: "Best overall for moderate swing speeds",
    specs: ["460cc; 10.5° or 12° (±2° adjustable)", "43 g Senior or 44 g Regular stock shaft", "Lightweight head, shaft and grip"],
    how: "The whole club is built light, so the same effort turns into more clubhead speed. It ranked near the top for forgiveness in MyGolfSpy's 2026 driver test.",
    drawback: "Expensive, and the light build gives little back to faster swingers.",
    src: "https://mygolfspy.com/reviews/drivers/taylormade-qi4d-max-lite/" }),
  P({ id: "optm-max-d", cat: "driver", short: "Cobra OPTM Max-D", name: "Cobra OPTM Max-D Driver", year: 2026, list: "$599",
    best: "Best for a slice",
    specs: ["10.5° or 12° (33 hosel settings, ±2°)", "Factory Senior (A) flex 40 g shaft option", "Fixed heel weight for draw bias"],
    how: "Cobra calls it the most draw-biased driver it has made, and it comes with a genuine senior-flex 40-gram shaft rather than an upcharge.",
    drawback: "If you don't slice, the strong draw bias can turn into a hook.",
    src: "https://www.golfdigest.com/story/cobra-optm-drivers--what-you-need-to-know" }),
  P({ id: "g440-sft-hl", cat: "driver", short: "PING G440 SFT HL", name: "PING G440 SFT HL Driver", year: 2025, list: "$619 at launch; PING cut G440 drivers to $449 in Aug 2026",
    best: "Best value from a premium maker",
    specs: ["9° or 10.5° (±1.5°)", "Alta Quick 35 or 45 shaft, Soft Regular", "Lighter build with draw bias"],
    how: "PING's High Launch build trims weight from head, shaft and grip. PING says slower swingers picked up about 9 yards with it, and the 2026 price cut makes it the best-value major-brand driver here.",
    drawback: "No 12° head, and the model is two seasons old.",
    src: "https://ping.com/en-us/golf-clubs/drivers/g440-sft-hl-driver" }),
  P({ id: "xxio-14", cat: "driver", short: "XXIO 14", name: "XXIO 14 Driver", year: 2025, list: "$799.99",
    best: "Lightest premium driver",
    specs: ["9.5°, 10.5° or 11.5° (±1.5°)", "36 g Regular shaft; 283 g total weight", "First XXIO with an adjustable hosel"],
    how: "XXIO designs only for moderate swing speeds. At 283 grams total, it's the lightest of the big-brand drivers here.",
    drawback: "The most expensive driver on the list.",
    src: "https://golf.com/gear/xxio-14-pushes-lightweight-tech-first-adjustable-driver/" }),
  P({ id: "quantum-max-fast", cat: "driver", short: "Callaway Quantum Max Fast", name: "Callaway Quantum Max Fast Driver", year: 2026, list: "$699.99",
    best: "Lightest Callaway driver",
    specs: ["10.5° or 12°", "40 g Mitsubishi Vanquish shaft (men's) or Eldio (women's)", "Light build with draw bias"],
    how: "Callaway aims it at moderate speeds that need help launching the ball. It replaced the Elyte Max Fast in February 2026.",
    drawback: "Pricey, and fewer independent reviews than the others so far.",
    src: "https://www.golfdiscount.com/collections/golf-clubs/products/callaway-quantum-max-fast-driver-2026" }),
  P({ id: "exotics-lite", cat: "driver", short: "Tour Edge Exotics Lite", name: "Tour Edge Exotics Lite Driver", year: 2026, list: "$499.99",
    best: "Rare 15° loft option",
    specs: ["10.5°, 12° or 15°", "About 40 g Fujikura shaft (Senior, R or S)", "Offset hosel and heel weight", "Right-handed only"],
    how: "Ultralight and offset to fight a slice, with a 15° head that almost no one else sells. Very slow swingers often carry it farther than a 10.5°.",
    drawback: "The offset look puts some golfers off, and fitting carts are harder to find.",
    src: "https://golfwrx.com/767723/tour-edge-unveils-new-exotics-metalwoods-and-irons/" }),
  P({ id: "hot-launch-max-d", cat: "driver", short: "Tour Edge Hot Launch Max D", name: "Tour Edge Hot Launch Max D Driver", year: 2026, list: "$299.99",
    best: "Best budget driver",
    specs: ["10.5°, 12° or 15° (left-handed: 10.5° only)", "Aldila Ascent shaft, 45–55 g", "Offset with draw bias"],
    how: "About half the price of the major brands, with the same high-loft, anti-slice recipe.",
    drawback: "Confirm a senior flex is available before you order; the launch material didn't list flexes.",
    src: "https://drivingrangeheroes.com/tour-edge-unveils-hot-launch-max-drivers-fairways-and-hybrids/" }),

  // ---------- Fairway woods ----------
  P({ id: "g440-max-fw-hl", cat: "fairway", short: "PING G440 Max fairway (HL)", name: "PING G440 Max Fairway Wood (HL build)", year: 2025, list: "$385 at launch; $299 after PING's Aug 2026 price cut",
    best: "Best range of high-lofted woods",
    specs: ["3W 15° to 9W 24°", "HL build with Alta Quick shafts", "±1.5° adjustable"],
    how: "Offers a 7-wood and 9-wood in the light HL build, the easiest way to replace hard-to-hit long irons.",
    drawback: "2025 technology, though PING's discount offsets that.",
    src: "https://golfwrx.com/752612/ping-announces-g440-fairway-woods-hybrids/" }),
  P({ id: "qi4d-max-lite-fw", cat: "fairway", short: "TaylorMade Qi4D Max Lite fairway", name: "TaylorMade Qi4D Max Lite Fairway Wood", year: 2026, list: "$379.99",
    best: "Lightest TaylorMade fairway",
    specs: ["15°, 18°, 21° or 24° (24° right-handed only)", "4° adjustable sleeve", "Reduced mass build"],
    how: "Matches the Max Lite driver's light build, so the swing feels the same off the tee and the fairway.",
    drawback: "Nothing above 24° (a 9-wood loft).",
    src: "https://www.golfdigest.com/story/taylormade-qi4d-fairway-wood-hybrids-equipment-rundown" }),
  P({ id: "hot-launch-max-d-fw", cat: "fairway", short: "Tour Edge Hot Launch Max D fairway", name: "Tour Edge Hot Launch Max D Fairway Wood", year: 2026, list: "$179.99",
    best: "Best value, up to an 11-wood",
    specs: ["3W 16° up to 11W 27°", "Offset with draw bias", "Left-handed up to the 7-wood only"],
    how: "The widest spread of high lofts at the lowest price, including an 11-wood that launches easily from the fairway.",
    drawback: "Budget brand with less fitting support.",
    src: "https://drivingrangeheroes.com/tour-edge-unveils-hot-launch-max-drivers-fairways-and-hybrids/" }),

  // ---------- Hybrids ----------
  P({ id: "g440-hybrid-hl", es: { best: "El mejor híbrido", list: "US$325 al salir; US$269 tras la rebaja de PING (ago. 2026)", specs: ["Del 2H 17° al 7H 34°", "Versión liviana HL del 3H al 7H", "Del 5H al 7H con sesgo de draw"], how: "Con lofts hasta 34° puede reemplazar hierros hasta el 6 o el 7, y la versión HL lo mantiene liviano.", drawback: "Modelo de 2025." }, cat: "hybrid", short: "PING G440 hybrid (HL)", name: "PING G440 Hybrid (HL build)", year: 2025, list: "$325 at launch; $269 after PING's Aug 2026 price cut",
    best: "Best overall hybrid",
    specs: ["2H 17° to 7H 34°", "HL build available 3H–7H", "5H–7H are draw-biased"],
    how: "High lofts up to 34° mean it can replace irons down to the 6 or 7, and the HL build keeps it light.",
    drawback: "2025 model.",
    src: "https://ping.com/en-us/golf-clubs/hybrids/g440-hybrid" }),
  P({ id: "qi4d-max-lite-rescue", cat: "hybrid", short: "TaylorMade Qi4D Max Lite Rescue", name: "TaylorMade Qi4D Max Lite Rescue", year: 2026, list: "$299.99",
    best: "Light hybrid with high lofts",
    specs: ["23°, 26°, 30° or 34° (30° and 34° right-handed only)", "Women's version available", "Light build"],
    how: "Lofts up to 34° let you swap out mid-irons, not just the 3 and 4.",
    drawback: "Left-handers can't get the two highest lofts.",
    src: "https://www.golfdigest.com/story/taylormade-qi4d-fairway-wood-hybrids-equipment-rundown" }),
  P({ id: "halo-xl-hywood", cat: "hybrid", short: "Cleveland Halo XL Hy-Wood", name: "Cleveland Halo XL Hy-Wood", year: 2024, list: "About $210–240",
    best: "Easiest launch from the rough",
    specs: ["Fairway-wood/hybrid crossover head", "3+ 17°, 4+ 20°, 5+ 23°, 6+ 26°", "High launch with draw bias"],
    how: "A bigger, wood-shaped head on a shaft between hybrid and fairway-wood length (about 41–42.5 inches). It sits up well in thick lies and gets the ball airborne with little effort.",
    drawback: "Older model, and the longer shaft takes some getting used to.",
    src: "https://golf.com/clubpage/cleveland-halo-xl-fairway-woods-reviews-player-testing-2025/" }),
  P({ id: "hot-launch-max-d-hybrid", cat: "hybrid", short: "Tour Edge Hot Launch Max D hybrid", name: "Tour Edge Hot Launch Max D Hybrid", year: 2026, list: "$159.99",
    best: "Best budget hybrid",
    specs: ["3H 19° to 6H 28°", "Offset with draw bias", "Right- and left-handed"],
    how: "Costs about half as much as the majors and is built to correct a slice.",
    drawback: "Highest loft is 28°, so it won't replace a 7-iron.",
    src: "https://drivingrangeheroes.com/tour-edge-unveils-hot-launch-max-drivers-fairways-and-hybrids/" }),

  // ---------- Irons ----------
  P({ id: "qi-max-hl-irons", es: { best: "Los mejores hierros para seniors", list: "Unos US$157 por palo (acero)", specs: ["Hierro 7 de 31°, hasta 3° más loft que el Qi Max normal", "Grafito REAX HL (flex Senior) o acero KBS Max Lite", "Cara alta para levantar la bola"], how: "Más loft y una cara alta e indulgente levantan la bola y la hacen caer suave, justo lo que más le cuesta a un swing lento.", drawback: "Con más loft cada número llega un poco menos; mide por yardas, no por el número del palo." }, cat: "irons", short: "TaylorMade Qi Max HL irons", name: "TaylorMade Qi Max HL Irons", year: 2026, list: "About $157 per club in steel",
    best: "Best overall irons for seniors",
    specs: ["7-iron 31°, up to 3° weaker than the regular Qi Max", "REAX HL graphite (Senior flex) or KBS Max Lite steel", "Tall face for launch"],
    how: "Weaker lofts plus a tall, forgiving face get the ball up and landing softly, the two things slower swings struggle with most.",
    drawback: "Weaker lofts mean less distance per number, which is fine if you judge by yards, not by the number on the sole.",
    src: "https://www.golfdigest.com/story/taylormade-qi-max-and-qi-max-hl-irons-what-you-need-to-know" }),
  P({ id: "halo-xl-full-face", cat: "hybrid-irons", short: "Cleveland Halo XL Full-Face irons", name: "Cleveland Halo XL Full-Face Irons", year: 2024, list: "About $129 per club",
    best: "Best hybrid-iron set",
    specs: ["Hollow, hybrid-shaped heads", "Grooves across the whole face", "Lightweight graphite"],
    how: "Each iron looks and behaves like a small hybrid, which is the easiest way to get mid-irons airborne. Full-face grooves help shots struck off the toe.",
    drawback: "No 2026 successor yet, so it's an older design.",
    src: "https://golf.com/clubpage/cleveland-zipcore-xl-halo-xl-full-face-irons-reviews/" }),
  P({ id: "hot-launch-max-d-irons", cat: "hybrid-irons", short: "Tour Edge Hot Launch Max D iron-woods", name: "Tour Edge Hot Launch Max D Iron-Woods", year: 2026, list: "$699.99 graphite (7 clubs)",
    best: "Best value hybrid-iron set",
    specs: ["7-piece set; 5-iron 26°", "Aldila Ascent graphite 50–60 g or steel", "Hollow heads, cambered sole"],
    how: "A full set of hollow, hybrid-like irons for roughly the price of four premium irons.",
    drawback: "Flex options weren't listed at launch, so confirm a senior flex.",
    src: "https://calgolfnews.com/tour-edge-drops-hot-launch-max-max-d-irons/" }),
  P({ id: "quantum-max-fast-irons", cat: "irons", short: "Callaway Quantum Max Fast irons", name: "Callaway Quantum Max Fast Irons", year: 2026, list: "$1,249.99 (set)",
    best: "Lightest Callaway irons",
    specs: ["5-9, PW, AW, GW, SW", "40 g Mitsubishi Vanquish graphite, Light flex", "Right-handed only"],
    how: "Callaway's lightest irons, built to launch high at moderate speeds, with a matching women's version.",
    drawback: "One stock shaft and right-handed only.",
    src: "https://odyssey.callawaygolf.com/product/irons-2026-quantum-max-fast" }),
  P({ id: "g740-irons", cat: "irons", short: "PING G740 irons", name: "PING G740 Irons", year: 2026, list: "$217 per club in graphite",
    best: "Most forgiving PING iron",
    specs: ["Sole 22% wider than PING's G440 iron", "Standard, Power or Retro loft options", "Alta CB graphite stock"],
    how: "PING's super-game-improvement iron with a wide sole that glides through the turf instead of digging.",
    drawback: "Pricey per club, and PING lists no dedicated light HL shaft for it.",
    src: "https://www.todays-golfer.com/news-and-events/equipment-news/ping-g740-irons-everything-you-need-to-know" }),
  P({ id: "xxio-14-irons", cat: "irons", short: "XXIO 14 irons", name: "XXIO 14 Irons", year: 2025, list: "$1,199.99 (6-PW)",
    best: "Lightest premium irons",
    specs: ["7-iron 28°", "About 48 g MP1400 graphite, R or S", "Matches the XXIO 14 driver"],
    how: "Ultra-light graphite throughout for golfers who feel tired late in the round.",
    drawback: "Very expensive.",
    src: "https://www.golfdiscount.com/collections/golf-clubs/products/xxio-14-irons" }),

  // ---------- Wedges ----------
  P({ id: "smart-sole-ff", cat: "wedge", short: "Cleveland Smart Sole Full-Face", name: "Cleveland Smart Sole Full-Face Wedge", year: 2024, list: "$129.99–139.99",
    best: "Easiest wedge around the green",
    specs: ["C 42° chipper, G 50°, S 58°, L 64°", "Wide three-tier sole", "Steel or UST Recoil Dart graphite"],
    how: "A very wide sole that's hard to dig or skull, ideal for chips and greenside bunkers.",
    drawback: "Not built for full swings or precise distance control.",
    src: "https://www.fairwaygolfusa.com/category/select/pid/729310" }),
  P({ id: "cleveland-cbz", cat: "wedge", short: "Cleveland CBZ", name: "Cleveland CBZ Wedge", year: 2025, list: "$179.99",
    best: "Forgiving wedge for full swings",
    specs: ["Cavity back, 44°–60°", "Full-Face version 50°–60°", "Graphite options incl. ladies"],
    how: "Cavity-back forgiveness in a normal-looking wedge, so it matches game-improvement irons.",
    drawback: "Less spin control than a blade-style wedge.",
    src: "https://golfwrx.com/765330/cleveland-announces-cbz-wedges-with-z-alloy-technology/" }),

  // ---------- Complete sets ----------
  P({ id: "wilson-profile-senior", es: { best: "El mejor set senior económico", list: "US$599.99 (suele estar en oferta)", specs: ["Driver, madera 5, híbrido 5, hierros 6-9, PW, SW, putter y bolsa de carro", "Varillas de grafito flex Senior", "Grips suaves"], how: "Uno de los pocos sets completos con flex senior de verdad y bolsa de carro, a precio de principiante.", drawback: "Tecnología básica comparada con comprar los palos uno por uno." }, cat: "set", short: "Wilson Profile Complete Senior", name: "Wilson Profile Complete Senior Set (2025)", year: 2025, list: "$599.99 (often on sale)",
    q: "Wilson Profile senior complete golf set",
    best: "Best budget senior set",
    specs: ["Driver, 5W, 5H, 6-9, PW, SW, putter, cart bag", "Senior-flex graphite", "Soft grips"],
    how: "One of the few box sets with a true senior flex and a cart bag, at a beginner-friendly price.",
    drawback: "Basic club technology compared with buying clubs one by one.",
    src: "https://www.pgatoursuperstore.com/wilson-2025-profile-complete-senior-with-cart-bag/2000000052600.html" }),
  P({ id: "tour-edge-te200", cat: "set", short: "Tour Edge Senior TE-200", name: "Tour Edge Senior TE-200 Complete Set", year: null, list: "$599.99",
    best: "Most hybrid-friendly senior set",
    specs: ["11.5° driver, 3W, 5W, 5H, 6-PW, SW, putter, cart bag", "All graphite, Senior flex"],
    how: "Comes with two fairway woods and a hybrid, the make-up most fitters suggest for slower swings.",
    drawback: "We couldn't confirm the model year.",
    src: "https://www.carlsgolfland.com/tour-edge-senior-te-200-complete-golf-package-set" }),
  P({ id: "cobra-fly-xl", cat: "set", short: "Cobra Fly-XL set", name: "Cobra Fly-XL Complete Set", year: 2025, list: "$999",
    best: "Best premium box set",
    specs: ["Driver (10.5°, or 11.5° in Lite), 3W, 4-5H, 6-PW, SW, putter, bag", "Regular or Lite (senior) graphite", "+1 inch length option"],
    how: "Closer to individually bought clubs than most box sets, with a Lite flex and a longer-length option for tall players.",
    drawback: "Expensive for a box set.",
    src: "https://www.cobragolf.com/products/fly-xl-complete-set-stand-bag-2025" }),
  P({ id: "strata-ultimate", cat: "set", short: "Callaway Strata Ultimate", name: "Callaway Strata Ultimate 16-Piece Set", year: null, list: "$699.99",
    best: "Best-known starter set",
    specs: ["Titanium driver, fairway wood, 2 hybrids, 6-SW, mallet putter, stand bag", "Graphite shafts", "Men's and women's versions"],
    how: "A widely sold, complete starter set from a major brand.",
    drawback: "Men's set comes in Regular flex only, which is stiff for many seniors.",
    src: "https://www.parwestgolf.com/products/mens-strata-ultimate-16-piece-set" }),

  // ---------- Women ----------
  P({ id: "ping-g-le4-driver", cat: "driver", short: "PING G Le4 driver", name: "PING G Le4 Driver (women's)", year: 2026, list: "$599",
    best: "Best women's driver under 80 mph",
    specs: ["11.5° (±1.5°)", "Alta LE Lite or Ultra Lite shafts", "Matching woods, hybrids and irons"],
    how: "PING designs the G Le4 family for women swinging 80 mph or less, the speed range most senior women fall into.",
    drawback: "Too light for women who swing faster than about 80 mph.",
    src: "https://golf.com/gear/pings-gle4-family-increased-distance-forgiveness/" }),
  P({ id: "xxio-14-ladies", cat: "driver", short: "XXIO 14 Ladies driver", name: "XXIO 14 Ladies Driver", year: 2025, list: "$799.99",
    best: "Most loft options for women",
    specs: ["10.5°, 11.5°, 12.5° or 13.5°", "35 g Ladies or 37 g A-flex shaft", "259–264 g total weight"],
    how: "Four lofts up to 13.5° and one of the lightest builds sold, for women who need help getting the ball in the air.",
    drawback: "Expensive.",
    src: "https://www.golfdiscount.com/collections/all/products/xxio-womens-xxio-14-driver" }),
  P({ id: "optm-max-d-women", cat: "driver", short: "Cobra Women's OPTM Max-D", name: "Cobra Women's OPTM Max-D Driver", year: 2026, list: "$599",
    best: "Best women's driver for a slice",
    specs: ["12°, adjustable 10°–14°", "42.5 g Ladies flex shaft", "44 inches"],
    how: "Strong draw bias and a wide loft range in a women's-length build.",
    drawback: "Can over-correct if you don't slice.",
    src: "https://www.golfdiscount.com/products/cobra-womens-optm-max-d-driver-2026" }),
  P({ id: "kalea-gold", cat: "set", short: "TaylorMade Kalea Gold set", name: "TaylorMade Kalea Gold Women's Set", year: 2024, list: "$1,899.99",
    best: "Best premium women's set",
    specs: ["10 pieces incl. adjustable driver", "Spider putter", "Lightweight women's shafts"],
    how: "A full premium set designed for women with moderate speeds, so the clubs match from driver to putter.",
    drawback: "Premium price.",
    src: "https://www.parwestgolf.com/blogs/content/taylormade-kalea-gold-review" }),
  P({ id: "callaway-reva", cat: "set", short: "Callaway REVA set", name: "Callaway REVA Women's Set (11-piece)", year: null, list: "$1,499.99",
    best: "Women's set in three lengths",
    specs: ["Short, standard and long lengths (right-handed)", "Left-handed in standard length only", "8-piece version $1,299.99"],
    how: "Three lengths matter: a set that fits your height gives more consistent contact than a one-size box set.",
    drawback: "We couldn't confirm the model year.",
    src: "https://www.parwestgolf.com/blogs/content/womens-complete-sets-2026-taylormade-kalea-gold-vs-callaway-reva-vs-rbz-honest-buyers-guide" }),

  // ---------- Putters ----------
  P({ id: "hb-soft-2-retreve", es: { best: "El mejor si te duelen las rodillas o la espalda", list: "US$149.99", specs: ["Un hueco en la cabeza saca la bola del hoyo", "Cabeza mallet indulgente", "Grip estándar"], how: "Pones la cabeza sobre la bola en el hoyo y la levantas: no tienes que agacharte decenas de veces por ronda.", drawback: "A algunos golfistas les distrae el hueco." }, cat: "putter-retreve", short: "Cleveland HB Soft 2 Retreve", name: "Cleveland HB Soft 2 Retreve Putter", year: 2024, list: "$149.99",
    best: "Best for bad knees and backs",
    specs: ["Hole in the mallet picks the ball out of the cup", "Forgiving mallet head", "Standard pistol grip"],
    how: "Press the head over the ball in the cup and lift; no bending down dozens of times a round.",
    drawback: "Some golfers find the cut-out look distracting.",
    src: "https://mygolfspy.com/news-opinion/cleveland-hb-soft-2-putters/" }),
  P({ id: "spider-zt-max-cb", cat: "putter", short: "TaylorMade Spider ZT Max Counterbalance", name: "TaylorMade Spider ZT Max Counterbalance Putter", year: 2026, list: "$500",
    best: "Most stable putter",
    specs: ["Zero-torque, high-MOI mallet", "36–38 inches, 398 g head", "46-inch long version also sold"],
    how: "Extra weight in the head and grip end steadies shaky hands and reduces twisting on off-center putts.",
    drawback: "The priciest putter here.",
    src: "https://www.golfdigest.com/story/taylormade-spider-tour-torched-zt-max-putters-preview" }),

  // ---------- Balls ----------
  P({ id: "e6-soft", cat: "ball", short: "Bridgestone e6 Soft", name: "Bridgestone e6 Soft Golf Balls", year: 2025, list: "$23.99 a dozen",
    best: "Straightest flight",
    specs: ["Very low compression (under 40)", "Low spin off the driver", "2-piece"],
    how: "Low driver spin keeps slices and hooks from curving as far.",
    drawback: "Little greenside spin.",
    src: "https://mygolfspy.com/uncategorized/bridgestone-e6-soft-golf-ball-gets-an-upgrade/" }),
  P({ id: "srixon-soft-feel", es: { best: "La mejor relación calidad-precio", list: "US$22.99–24.99 la docena", specs: ["Compresión 58 según el fabricante", "Dos piezas", "Versión 2025"], how: "Sensación suave y buen precio: una opción sensata para la mayoría de seniors.", drawback: "No es una bola de mucho efecto para el juego corto." }, cat: "ball", short: "Srixon Soft Feel", name: "Srixon Soft Feel Golf Balls", year: 2025, list: "$22.99–24.99 a dozen",
    best: "Best all-round value",
    specs: ["Compression 58, maker's spec (Lady version 56)", "2-piece", "2025 version"],
    how: "Soft feel and a fair price; a sensible default for most senior golfers.",
    drawback: "Not a spin ball for short-game experts.",
    src: "https://mygolfspy.com/news-opinion/srixon-soft-feel-golf-balls-what-you-need-to-know/" }),
  P({ id: "callaway-supersoft", cat: "ball", short: "Callaway Supersoft", name: "Callaway Supersoft Golf Balls", year: 2025, list: "About $25 a dozen",
    best: "Softest feel, most colors",
    specs: ["Very low compression", "10 colors, incl. high-visibility", "2-piece"],
    how: "The softest-feeling ball here, and bright colors are easier to follow in flight and find in the rough.",
    drawback: "MyGolfSpy found it about 1.4 mph slower than a Pro V1 off an 85-mph driver.",
    src: "https://calgolfnews.com/callaways-erc-soft-and-supersoft-for-2025/" }),
  P({ id: "titleist-trufeel", cat: "ball", short: "Titleist TruFeel", name: "Titleist TruFeel Golf Balls", year: 2024, list: "About $25 a dozen",
    best: "Softest Titleist",
    specs: ["About 65–70 compression", "2-piece", "AIM 360 alignment version (2026)"],
    how: "Titleist quality and feel at a two-piece price.",
    drawback: "Ranked 41st of 48 for wedge spin in one robot test.",
    src: "https://www.ballcaddie.com/blog/titleist-trufeel-review" }),
];

list.push(...extraA, ...extraB);
export const products = Object.fromEntries(list.map((p) => [p.id, p]));
export const byCat = (cat) => list.filter((p) => p.cat === cat).map((p) => p.id);
export const redirects = list.map((p) => ({ source: `/go/${p.go}`, destination: p.url, permanent: false }))
  .flatMap((r) => [r, { ...r, source: r.source + "/" }]);
